run_name: emb-exp-funcqa-aug-args

defaults:
  - model: llama2
  - augmentation: funcqa_specific
  - data: funcqa_oh

training:
  lr: 1e-4
  num_epochs: 1 # 10
  deepspeed_config: './configs/deepspeed/stage3_v2.json'
  embedding_augmentation_type: ${augmentation.embedding_augmentation_type}

out_checkpoint_dir: './checkpoints/${run_name}/${data.dataset_name}'
best_checkpoint_filepath: '${out_checkpoint_dir}/best_model.pt'

# independent variable
augmentation.embedding_augmentation_type: "augmented-only"
augmentation.aug_token_bias: 0.0